#-----------------------------------------------------------------------------
#  Configuration for continuous integration service at appveyor.com
#-----------------------------------------------------------------------------
version: 1.0.0.{build}

branches:
  only:
  - master

# Operating system (build VM template)
os: Visual Studio 2017

# scripts that are called at very beginning, before repo cloning
init:

# clone directory
clone_folder: c:\projects\eyden-tracer

platform: x64

#install:
#  -cmd: choco install OpenCV

environment:
  matrix:
    - ARCH: amd64
    - ARCH: x86

install:
  - set ORIGIN_PATH=%cd%
  - set PATH=%PATH%;c:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\
  - git submodule update --init --recursive
  - cd ..
  - git clone https://github.com/google/googletest.git
  - cd googletest
  - cmake -G "Visual Studio 14 2015" .
  - devenv.exe googletest\msvc\gtest-md.sln /Upgrade
  - devenv.exe googletest\msvc\gtest-md.sln /Build
  - mkdir googletest\lib
  - copy googletest\msvc\gtest-md\Debug\gtestd.lib googletest\lib\gtest.lib
  - copy googletest\msvc\gtest-md\Debug\gtest_main-mdd.lib googletest\lib\gtest_main.lib
  - set GTEST_ROOT=%cd%\googletest
  - cd %ORIGIN_PATH%

build_script:
  - choco install opencv
  - cd c:\projects\eyden-tracer
  - md build
  - cd build
  - cmake -DOpenCV_DIR=c:\tools\opencv\build -G"Visual Studio 15 Win64" -DUSE_OPENGL=ON ..
  - msbuild /m /p:Configuration=Release /p:Platform="x64" eyden-tracer.sln

test_script:
  - ctest -C Debug -VV

#test_script:
#  - cmd: |-
#      copy C:\tools\opencv\build\x64\vc15\bin\opencv_world???.dll  ".\bin\Release"
#      copy C:\tools\opencv\build\x64\vc15\bin\opencv_world???d.dll ".\bin\Debug"
#      .\bin\Release\Tests.exe --gtest_output=xml:tests.xml > tests.txt

#after_test:
#  - ps: |
#      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
#      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
#      bash codecov.sh -f "tests.xml" -t 7f81e53e-1ebf-44f8-8b49-54da37b0a0a8

#on_finish:
#  - ps: (new-object net.webclient).UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path c:\projects\eyden-tracer\build\tests.xml))
